/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ProjectStatusDto } from '../models/project-status-dto';
import { UserDto } from '../models/user-dto';
export interface ProjectDto {
  createdAt: string;
  description: string | null;
  id: string;
  name: string;
  owner: UserDto;
  status: ProjectStatusDto;
  updatedAt: string;
  users: Array<UserDto>;
}
