/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserRoleDto } from '../models/user-role-dto';
import { UserStatusDto } from '../models/user-status-dto';
export interface UserDto {
  createdAt: string;
  email: string;
  firstName: string;
  id: string;
  lastName: string;
  role: UserRoleDto;
  status: UserStatusDto;
  updatedAt: string;
}
